language: cpp

sudo: required
cache: ccache
dist: xenial

if: tag IS blank

jobs:
  include:
    - env: TARGET=linux64 USE_QT=qt5
      os: linux
      compiler: gcc
    - env: TARGET=linux64 USE_QT=qt5
      os: linux
      compiler: clang
    - env: TARGET=linux64 USE_QT=qt4
      os: linux
    - env: TARGET=linux64 USE_GTK=gtk3
      os: linux
    - env: TARGET=linux64 USE_GTK=gtk2
      os: linux
    - env: TARGET=linux64 USE_DAEMON=jsonrpc
      os: linux
      compiler: gcc
    - env: TARGET=linux64 USE_DAEMON=jsonrpc
      os: linux
      compiler: clang
    - env: TARGET=macos64
      os: osx
      osx_image: xcode9.4
    - env: TARGET=macos64
      os: osx
      osx_image: xcode10.3
    - env: TARGET=macos64
      os: osx
      osx_image: xcode11.2
    - env: TARGET=windows32
      os: linux
    - env: TARGET=windows64
      os: linux

install:
  - ./tests/travis-ci/install-build-depends.sh

script:
  - ./tests/travis-ci/build-and-test.sh
